apiVersion: v1
kind: ConfigMap
metadata:
  name: computax-config
data:
  azure.activedirectory.client-id: 668fc0b3-5b1d-4d0a-877a-c676c49ed70a
  azure.activedirectory.client-secret: hXI8Q~6pFGxVpmlmkiOPRVdbul48Ijsj0QG6RaTv
  azure.activedirectory.tenant-id: bbc71867-6864-4f71-9cb3-bf21da49f4f5
  redis.connection.host: ci-st-comp-redis001.redis.cache.windows.net
  #redis.connection.key: 8vMdYSCOWXXHN1BMt/gv66vWcZgTnQ4wXNduv88ZE6hPP3IiljcxlGan0t7eqzlBPxjGLT+HnmeuaB6jMfQk1A==
  redis.connection.password: qG6W2WDwNjdQrObiSBct3mgymZ2QNJzzGKlr0TO0OMY=
  redis.connection.port: "6380"
  redis.connection.ssl: "true"
  spring.datasource.password: '{9ujLmWD$yH2t6'
  spring.datasource.url: jdbc:sqlserver://ci-st-dct-db001.database.windows.net:1433;databaseName=DCTMasterDB_UAT;columnEncryptionSetting=Enabled;keyVaultProviderClientId=55ba31b5-c5b7-4eda-9e71-133e8a3f4c6e;keyVaultProviderClientKey={6q98Q~cXyAfOcfJk.ch.B~n-UEXp.nfciim42brX};
  spring.datasource.username: Appuser_EYDCTMasterUAT
  spring.flyway.password: QzNDqG283Ms4
  spring.flyway.url: jdbc:sqlserver://ci-st-dct-db001.database.windows.net:1433;databaseName=AY20200003_DctTenantDB_UAT
  spring.flyway.user: Appuser_EYDCTAY20200003UAT
  spring.flyway.enabled: "false"
  tenant.spring.datasource.connection-timeout: "30000"
  tenant.spring.datasource.idle-timeout: "600000"
  tenant.spring.datasource.maximum-pool-size: "50"
  tenant.spring.datasource.minimum-idle-size: "10"
  tenant.default: uatxebiacomputax.dvtfo.onmicrosoft.com
  #tenant.default: uatptcomputax.dvtfo.onmicrosoft.com
  tenant.org.hibernate.envers.default_schema: "audit"
  tar-service-endpoint: "http://tar-service.computax.svc.cluster.local/"
  coi-service-endpoint: "http://coi-service.computax.svc.cluster.local/"
  client-onboarding-service-endpoint: "http://client-onboarding-service.computax.svc.cluster.local/"
  tenant-admin-endpoint: "http://tenant-admin.computax.svc.cluster.local/"
  workflow-endpoint: "http://workflow-service.computax.svc.cluster.local/"
  admin-api-endpoint: "http://api-admin-computax.computax.svc.cluster.local/"
  advancetax-endpoint: "http://advancetax-service.computax.svc.cluster.local/"
  tax-provision-service-endpoint: "http://tax-provision-service.computax.svc.cluster.local/"
  async-service-endpoint: "http://async-service.computax.svc.cluster.local/"
  messaging-queue-service-endpoint: "http://messaging-queue-service.computax.svc.cluster.local/"
  coi-pdf-service-endpoint: "http://coi-pdf-service.computax.svc.cluster.local/"
  fs-autofill-service-endpoint: "http://fs-autofill-service.computax.svc.cluster.local/"
  tar.division.data.path: "clauses/get-division-data-size/{entityId}?finYearId={finYearId}"
  spring-mail-host: smtp.office365.com
  spring-mail-port: "587"
  spring-mail-username: devtfo@eyindiaonetax.com
  spring-mail-password: AKld8ngzYy7X2^4n
  spring-mail-properties-mail-smtp-auth: "true"
  spring-mail-properties-mail-smtp-starttls-enable: "true"
  sharepoint.master.tenant: eytfo.onmicrosoft.com
  sharepoint.master.template.path: /sites/eytfo.sharepoint.com:/sites/EYDigiCompuTax_UAT/
  sharepoint.client.id: 1a8046ae-ca7a-4865-9bf5-80c9a842682a
  sharepoint.client.secret: pya8Q~YGRgjR22la6~1qGa9xvnIDx-pVh5Xp_cOM
  aspose.license.filename: Aspose.Cells.Java.lic
  aspose.words.license.filename: Aspose.Words.Java.lic
  aspose.pdf.license.filename: Aspose.PDF.Java.lic
  database.activiti.schema.update: "false"
  database.activiti.historyLevel: "full"
  tenant.spring.jpa.generate-ddl: "true"
  tenant.spring.jpa.show-sql: "false"
  timeout.summary.file.download: "1"
  server.http.methods.allowed: GET,POST,DELETE,PATCH,PUT
  parallel.login.ignore.user: user4@uatxebiacomputax.dvtfo.onmicrosoft.com
  server.servlet.session.cookie.http-only: "true"
  app.allowed.origins: "https://uatcomputax.eyasp.in/"
  file.size.boundary.inMb: "1"
  pdf.generation.screen.batch.size: "11"
  powerbi.financialyear.limit: "2010"
  tis.validation.flag: "false"
  pdf.generation.file.size.inMb: "10"
  #ASB Config
  file.request.servicebus.connection-string: Endpoint=sb://ci-st-digict-sb01.servicebus.windows.net/;SharedAccessKeyName=RootManageSharedAccessKey;SharedAccessKey=6pLV31k1NdeHC52Le0PHj9QwNELMW90V9+ASbKs9UpU=;EntityPath=file-requests-queue
  file.request.servicebus.queue-name: file-requests-queue
  file.request.servicebus.client.partition.factor: "200"
  file.request.servicebus.clients.number: "1030"
  #Feign Client respective of service
  mq.feign.tar.service.url: "http://tar-service.computax.svc.cluster.local/"
  mq.feign.onboarding.service.url: "http://client-onboarding-service.computax.svc.cluster.local/"
  mq.feign.client.coi.url: "http://coi-service.computax.svc.cluster.local/coi/api/v1"
  mq.feign.client.advancetax.url: "http://advancetax-service.computax.svc.cluster.local/"
  mq.feign.client.processor.module.url: "/asb-file-upload/process"
  mq.coi.max.file.processing.limit: "4"
  mq.feign.client.processing.status.module.url: "/asb-file-upload/fetch-process-count"
  mq.feign.client.processing.info.module.url: "/asb-file-upload/pushInfo"
  mq.coi.base.url: "http://coi-file-service.computax.svc.cluster.local/coi/api/v1"
  mq.coi.api.url.excel: "/asb-file-upload/process"
  mq.coi.api.url.text: "/asb-file-upload/process-text-file"
  mq.coi.processing.limit: "4"
  mq.coi.api.url.processing.info: "/asb-file-upload/fetch-process-count"
  mq.coi.api.url.push.info: "/asb-file-upload/pushInfo"
  mq.tar.base.url: http://tar-service.computax.svc.cluster.local/tar/api/v1
  mq.tar.api.url.excel: /asb-file-upload/process
  mq.tar.processing.limit: "4"
  mq.tar.api.url.processing.info: /asb-file-upload/fetch-process-count
  mq.tar.api.url.push.info: /asb-file-upload/pushInfo
  tis.password.flag: "true"
  tis.data.limit: "10"  
  prefilljson.validation.flag: "true"
  power-bi.export.uri: "https://api.powerbi.com/v1.0/myorg/reports/{reportId}/ExportTo"
  power-bi.export.status.uri: "https://api.powerbi.com/v1.0/myorg/reports/{reportId}/exports/{exportId}"
  power-bi.export.file.uri: "https://api.powerbi.com/v1.0/myorg/reports/{reportId}/exports/{exportId}/file"
  power-bi.export.file.thread.sleep.interval: "4000"
  refresh.reload.flag : "true"
  refresh.reload.operation.flag : "true"
  refresh.reload.conditional.operation.flag : "true"
  refresh.reload.summary.flag : "true"
  itp.tenant.exclude.id : 0,7
  report-endpoint: "http://report-service.computax.svc.cluster.local/"
  tar.workflow.dashboard.url: "/workflow-dashboard/level"
  tar.onboarding.answers.url: "/answers/tar-onboarding-itp"
  itp.summary.donut.path: "summary/donut-chart-itp"
  ais.json.validation.flag: "true"
  feign.itp.service.name : ITP ME Service
  feign.itp.service.url : http://uatdigict-itp.konarkdev.net/oneTaxPlatform/v1/
  feign.report.service.name: report-service
  feign.report.service.url: http://report-service.computax.svc.cluster.local/report/api/v1/
  itp.cookie.name : "user-token"
  itp.request.queue-name : "digidct-app-genreq"
  itp.response.queue-name : "digidct-app-genresp"
  itp.request.queue.connection-string : Endpoint=sb://ci-st-itp-sb01.servicebus.windows.net/;SharedAccessKeyName=digidct-app-genreq-listen;SharedAccessKey=VjgtIZ68p5lz3Q5+wW8GPfvf4vVwOnVHg+ASbBaVJF4=;EntityPath=digidct-app-genreq
  itp.response.queue.connection-string : Endpoint=sb://ci-st-itp-sb01.servicebus.windows.net/;SharedAccessKeyName=digidct-app-genresp-listen;SharedAccessKey=q7+NwF5biRc5TyhRYtnOjIKUDR0w6xpZN+ASbH3WJjs=;EntityPath=digidct-app-genresp
  mq.admin.base.url: "http://api-admin-computax.computax.svc.cluster.local/admin/api/v1"
  mq.tenant.base.url: "http://tenant-admin.computax.svc.cluster.local/tenant-admin/api/v1"
  mq.admin.api.url.group: "/itp/groups"
  mq.tenant.api.url.entity: "/itp/entities"
  mq.tenant.api.url.user: "/itp/users"
  mq.tenant.api.url.dashboard: "/itp/dashboard"
  mq.tenant.api.url.bulk_onboarding_user: "/itp/bulk-onboarding"
  itp.dashboard.request.queue-name: "digidct-app-dashboard-genreq"
  itp.dashboard.response.queue-name: "digidct-app-dashboard-genresp"
  itp.dashboard.request.queue.connection-string: Endpoint=sb://ci-st-itp-sb01.servicebus.windows.net/;SharedAccessKeyName=root;SharedAccessKey=vkH5XQeTO/phBkLbebll62RO8PlSydKFb+ASbF8fpzs=;EntityPath=digidct-app-dashboard-genreq
  itp.dashboard.response.queue.connection-string: Endpoint=sb://ci-st-itp-sb01.servicebus.windows.net/;SharedAccessKeyName=root;SharedAccessKey=HWPTxjBJe42qhYu7cXxo6pz5EgcYOYIfA+ASbKa6HAY=;EntityPath=digidct-app-dashboard-genresp
  redis.enabled.flag: "false"
  redis.expiration.inMillisec: "6000"
  tar.upload.request.queue-name: "tar-file-requests-queue"
  tar.upload.queue.connection-string: Endpoint=sb://ci-st-itp-sb01.servicebus.windows.net/;SharedAccessKeyName=tar-file-requests-queue;SharedAccessKey=0e3F5X4U0Mm4ZXloW98y0YFeFSTNVX/4O+ASbKlYf74=;EntityPath=tar-file-requests-queue
  itp.bulk-onboard.request.queue-name: "digidct-app-genreq"
  itp.bulk-onboard.response.queue-name: "digidct-app-genresp"
  itp.bulk-onboard.request.queue.connection-string: Endpoint=sb://ci-st-itp-sb01.servicebus.windows.net/;SharedAccessKeyName=digidct-app-genreq-listen;SharedAccessKey=VjgtIZ68p5lz3Q5+wW8GPfvf4vVwOnVHg+ASbBaVJF4=;EntityPath=digidct-app-genreq
  itp.bulk-onboard.response.queue.connection-string: Endpoint=sb://ci-st-itp-sb01.servicebus.windows.net/;SharedAccessKeyName=digidct-app-genresp-listen;SharedAccessKey=q7+NwF5biRc5TyhRYtnOjIKUDR0w6xpZN+ASbH3WJjs=;EntityPath=digidct-app-genresp
  draft.json.validation: "true"
  spring.logging.level: "INFO"
  hibernate.logging.level: "INFO"
  root.logging.level: "INFO"
  tpRnR.enabled.flag: "true"
  fsAutoFillBaseMapping: "https://uatcomputax.eyasp.in/computax/fs-autofill-service/api/v1/api-based/"
  fsAutoFillBaseApiPb: "https://uatcomputax.eyasp.in/api"
  fsAutoFillBaseFile: "https://uatcomputax.eyasp.in/computax/fs-autofill-service/api/v1/files/api-based/"


  key_vault_name: "ci-st-tds-aigen-kv01"
  key_vault_url: "https://ci-st-tds-aigen-kv01.vault.azure.net/"
  key_vault_tennant_id: "68993871-e3b7-415e-88ea-30d7f913d421"
  key_vault_client_id: "844b53e1-a4c8-4e72-83c7-96818fe86f09"
  key_vault_client_secret: vPc8Q~yzCULAckKIpUAYJLOrEOWbGgi_woWOIb0m