#config production.
apiVersion: v1
kind: ConfigMap
metadata:
  name: computax-config
data:
  azure.activedirectory.client-id: f68665ac-8c60-46a5-8207-a93751fddf13
  azure.activedirectory.client-secret: deE5yD~b.Kg-g31~.RQYP-4g031_KyHT_k
  azure.activedirectory.tenant-id: e29e4c95-e51f-4486-853d-9eb06c8482d2
  redis.connection.host: ci-pr-digict-redis01.redis.cache.windows.net
  #redis.connection.key: 8vMdYSCOWXXHN1BMt/gv66vWcZgTnQ4wXNduv88ZE6hPP3IiljcxlGan0t7eqzlBPxjGLT+HnmeuaB6jMfQk1A==
  redis.connection.password: lZqpMGmd17PuhfWcV75xR65r9eb9Ci2b1AzCaB0TIs8=
  redis.connection.port: "6380"
  redis.connection.ssl: "true"
  spring.datasource.password: 3[eGrLN!jE[4#Ys4
  spring.datasource.url: jdbc:sqlserver://ci-pr-tfo-db01.database.windows.net:1433;databaseName=DCTMasterDB;columnEncryptionSetting=Enabled;keyVaultProviderClientId=d28fc98d-7ab3-4a47-ba29-f73368273823;keyVaultProviderClientKey={clX8Q~EIOEi_brSu4cs6B0ktBrKL17-DPX2CMad~};
  spring.datasource.username: Appuser_DCTMasterDB
  spring.flyway.password: 7uj6tjuM98uYtgs
  spring.flyway.url: jdbc:sqlserver://ci-pr-tfo-db01.database.windows.net:1433;databaseName=AY20200007_DctTenantDB
  spring.flyway.user: Appuser_AY20200007
  spring.flyway.enabled: "false"
  tenant.spring.datasource.connection-timeout: "30000"
  tenant.spring.datasource.idle-timeout: "600000"
  tenant.spring.datasource.maximum-pool-size: "50"
  tenant.spring.datasource.minimum-idle-size: "10"
  tenant.default: centralindia.eyindiaonetax.com
  tenant.org.hibernate.envers.default_schema: "audit"
  tar-service-endpoint: "http://tar-service.computax.svc.cluster.local/"
  coi-service-endpoint: "http://coi-service.computax.svc.cluster.local/"
  client-onboarding-service-endpoint: "http://client-onboarding-service.computax.svc.cluster.local/"
  tenant-admin-endpoint: "http://tenant-admin.computax.svc.cluster.local/"
  workflow-endpoint: "http://workflow-service.computax.svc.cluster.local/"
  admin-api-endpoint: "http://api-admin-computax.computax.svc.cluster.local/"
  advancetax-endpoint: "http://advancetax-service.computax.svc.cluster.local/"
  tax-provision-service-endpoint: "http://tax-provision-service.computax.svc.cluster.local/"
  async-service-endpoint: "http://async-service.computax.svc.cluster.local/"
  messaging-queue-service-endpoint: "http://messaging-queue-service.computax.svc.cluster.local/"
  coi-pdf-service-endpoint: "http://coi-pdf-service.computax.svc.cluster.local/"
  mq.tar.base.url: "http://tar-service.computax.svc.cluster.local/tar/api/v1"
  mq.tar.api.url.excel: /asb-file-upload/process
  mq.tar.processing.limit: "4"
  mq.tar.api.url.processing.info: /asb-file-upload/fetch-process-count
  mq.tar.api.url.push.info: /asb-file-upload/pushInfo
  spring-mail-host: smtp.office365.com
  spring-mail-port: "587"
  spring-mail-username: devtfo@eyindiaonetax.com
  spring-mail-password: AKld8ngzYy7X2^4n
  spring-mail-properties-mail-smtp-auth: "true"
  spring-mail-properties-mail-smtp-starttls-enable: "true"
  sharepoint.master.tenant: eytfo.onmicrosoft.com
  sharepoint.master.template.path: /sites/eytfo.sharepoint.com:/sites/EYDigiCompuTax_Prod/
  sharepoint.client.id: ebcef4b5-18ac-4c71-bd63-d641ab06a0a9
  sharepoint.client.secret: 1Fh8Q~eD-7uwD~-~.i5uuj5SekjU_EynMzryDdrv
  aspose.license.filename: Aspose.Cells.Java.lic
  aspose.words.license.filename: Aspose.Words.Java.lic
  aspose.pdf.license.filename: Aspose.PDF.Java.lic
  database.activiti.schema.update: "false"
  spring.jpa.properties.hibernate.show_sql: "false"
  spring.jpa.properties.hibernate.use_sql_comments: "true"
  spring.jpa.properties.hibernate.format_sql: "true"
  spring.jpa.properties.hibernate.type: "trace"
  timeout.summary.file.download: "15"
  app.iterationCount: "1956"
  app.secretKey: "GI2Ia46T1G4V8MS2"
  app.allowed.origins: "https://computax.eyindiaonetax.com/"
  file.size.boundary.inMb: "1"
  tis.password.flag: "false"
  refresh.reload.flag : "true"
  tis.data.limit: "10"
  prefilljson.validation.flag: "false"
  refresh.reload.operation.flag : "true"
  refresh.reload.conditional.operation.flag : "true"
  refresh.reload.summary.flag : "true"
  pdf.generation.screen.batch.size: "11"
  server.http.methods.allowed: GET,POST,DELETE,PATCH,PUT
  server.servlet.session.cookie.http-only: "true"
  #ASB Config
  file.request.servicebus.connection-string: Endpoint=sb://ci-pr-digict-sb01.servicebus.windows.net/;SharedAccessKeyName=RootManageSharedAccessKey;SharedAccessKey=BioE1r39OXPvvyk5N4TkC9omn2ymmY23C+ASbDwd3kI=;EntityPath=file-requests-queue
  file.request.servicebus.queue-name: file-requests-queue
  file.request.servicebus.client.partition.factor: "200"
  file.request.servicebus.clients.number: "1200"
  #Feign Client respective of service
  mq.feign.tar.service.url: "http://tar-service.computax.svc.cluster.local/"
  mq.feign.onboarding.service.url: "http://client-onboarding-service.computax.svc.cluster.local/"
  mq.feign.client.coi.url: "http://coi-service.computax.svc.cluster.local/coi/api/v1"
  mq.feign.client.advancetax.url: "http://advancetax-service.computax.svc.cluster.local/"
  mq.feign.client.processor.module.url: "/asb-file-upload/process"
  mq.coi.max.file.processing.limit: "2"
  mq.feign.client.processing.status.module.url: "/asb-file-upload/fetch-process-count"
  mq.feign.client.processing.info.module.url: "/asb-file-upload/pushInfo"
  mq.coi.base.url: "http://coi-file-service.computax.svc.cluster.local/coi/api/v1"
  mq.coi.api.url.excel: "/asb-file-upload/process"
  mq.coi.api.url.text: "/asb-file-upload/process-text-file"
  mq.coi.processing.limit: "2"
  mq.coi.api.url.processing.info: "/asb-file-upload/fetch-process-count"
  mq.coi.api.url.push.info: "/asb-file-upload/pushInfo"
  tis.validation.flag: "false"
  tis.password.flag: "true"
  prefilljson.validation.flag: "true"
  power-bi.export.uri: "https://api.powerbi.com/v1.0/myorg/reports/{reportId}/ExportTo"
  power-bi.export.status.uri: "https://api.powerbi.com/v1.0/myorg/reports/{reportId}/exports/{exportId}"
  power-bi.export.file.uri: "https://api.powerbi.com/v1.0/myorg/reports/{reportId}/exports/{exportId}/file"
  power-bi.export.file.thread.sleep.interval: "4000"
  powerbi.financialyear.limit: "2010"
  parallel.login.ignore.user: ""
  itp.tenant.exclude.id: ""
  tar.division.data.path: "clauses/get-division-data-size/{entityId}?finYearId={finYearId}"
  tar.workflow.dashboard.url: "/workflow-dashboard/level"
  tar.onboarding.answers.url: "/answers/tar-onboarding-itp"
  itp.summary.donut.path: "summary/donut-chart-itp"
  ais.json.validation.flag: "true"
  feign.itp.service.name : ITP ME Service
  feign.itp.service.url : http://digict-itp.konarklive.net/oneTaxPlatform/v1/
  feign.report.service.name: report-service
  feign.report.service.url: http://report-service.computax.svc.cluster.local/report/api/v1/
  itp.cookie.name : "user-token"
  itp.request.queue-name : "digidct-app-genreq"
  itp.response.queue-name : "digidct-app-genresp"
  itp.request.queue.connection-string : Endpoint=sb://ci-pr-itp-sb01.servicebus.windows.net/;SharedAccessKeyName=digidct-app-genreq;SharedAccessKey=7dnf1OtwOF9e8Mms4WEyzwYqifo3WrJ55+ASbOo99Xc=;EntityPath=digidct-app-genreq
  itp.response.queue.connection-string : Endpoint=sb://ci-pr-itp-sb01.servicebus.windows.net/;SharedAccessKeyName=digidct-app-genresp;SharedAccessKey=lA68OVOIWVvvZLzxH5OR0RPeA6txZTmyT+ASbGd319E=;EntityPath=digidct-app-genresp
  mq.admin.base.url: "http://api-admin-computax.computax.svc.cluster.local/admin/api/v1"
  mq.tenant.base.url: "http://tenant-admin.computax.svc.cluster.local/tenant-admin/api/v1"
  mq.admin.api.url.group: "/itp/groups"
  mq.tenant.api.url.entity: "/itp/entities"
  mq.tenant.api.url.user: "/itp/users"
  mq.tenant.api.url.dashboard: "/itp/dashboard"
  itp.dashboard.request.queue-name: "digidct-app-dashboard-genreq"
  itp.dashboard.response.queue-name: "digidct-app-dashboard-genresp"
  itp.dashboard.request.queue.connection-string: Endpoint=sb://ci-pr-itp-sb01.servicebus.windows.net/;SharedAccessKeyName=digidct-app-dashboard-genreq;SharedAccessKey=+O2m2hBLsVzqDyq3n1YGardAxfVHWD5Hs+ASbPUveoA=;EntityPath=digidct-app-dashboard-genreq
  itp.dashboard.response.queue.connection-string: Endpoint=sb://ci-pr-itp-sb01.servicebus.windows.net/;SharedAccessKeyName=digidct-app-dashboard-genresp;SharedAccessKey=Cfmsb2xmkFYujW1xT+fSrqKTis+5GViQ4+ASbOqVyjw=;EntityPath=digidct-app-dashboard-genresp
  redis.enabled.flag: "false"
  redis.expiration.inMillisec: "6000"
  tar.upload.request.queue-name: "tar-file-requests-queue"
  tar.upload.queue.connection-string: Endpoint=sb://ci-pr-itp-sb01.servicebus.windows.net/;SharedAccessKeyName=tar-file-requests-queue;SharedAccessKey=Mmk/bKXS+9AwhLjASvevp9Ok3aDdqmb0O+ASbOxXUj0=;EntityPath=tar-file-requests-queue
  itp.bulk-onboard.request.queue-name: "digidct-app-genreq"
  itp.bulk-onboard.response.queue-name: "digidct-app-genresp"
  itp.bulk-onboard.request.queue.connection-string: Endpoint=sb://ci-pr-itp-sb01.servicebus.windows.net/;SharedAccessKeyName=digidct-app-genreq;SharedAccessKey=7dnf1OtwOF9e8Mms4WEyzwYqifo3WrJ55+ASbOo99Xc=;EntityPath=digidct-app-genreq
  itp.bulk-onboard.response.queue.connection-string: Endpoint=sb://ci-pr-itp-sb01.servicebus.windows.net/;SharedAccessKeyName=digidct-app-genresp;SharedAccessKey=lA68OVOIWVvvZLzxH5OR0RPeA6txZTmyT+ASbGd319E=;EntityPath=digidct-app-genresp
  draft.json.validation: "true"
  spring.logging.level: "INFO"
  hibernate.logging.level: "INFO"
  root.logging.level: "INFO"
  report-endpoint: "http://report-service.computax.svc.cluster.local/"
  pdf.generation.file.size.inMb: "10"
  tpRnR.enabled.flag: "true"
  mq.tenant.api.url.bulk_onboarding_user: "/itp/bulk-onboarding"